/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ReviewChangeListRouteImport } from './routes/review-change-list'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as NewsRouteImport } from './routes/news'
import { Route as LoginRouteImport } from './routes/login'
import { Route as HelpRouteImport } from './routes/help'
import { Route as DownloadsRouteImport } from './routes/downloads'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as NoticeIdRouteImport } from './routes/notice.$id'
import { Route as AdminTodoCenterRouteImport } from './routes/admin.todo-center'
import { Route as AdminTenderDocRouteImport } from './routes/admin.tender-doc'
import { Route as AdminTemplateManageRouteImport } from './routes/admin.template-manage'
import { Route as AdminSystemSettingsRouteImport } from './routes/admin.system-settings'
import { Route as AdminSupplierProfileRouteImport } from './routes/admin.supplier-profile'
import { Route as AdminSupplierAuthorizationRouteImport } from './routes/admin.supplier-authorization'
import { Route as AdminSupervisorLogsRouteImport } from './routes/admin.supervisor-logs'
import { Route as AdminSupervisorHallRouteImport } from './routes/admin.supervisor-hall'
import { Route as AdminSupervisorAbnormalRouteImport } from './routes/admin.supervisor-abnormal'
import { Route as AdminSubAccountsRouteImport } from './routes/admin.sub-accounts'
import { Route as AdminReviewChangeListRouteImport } from './routes/admin.review-change-list'
import { Route as AdminProjectsRouteImport } from './routes/admin.projects'
import { Route as AdminProcurementRequirementsRouteImport } from './routes/admin.procurement-requirements'
import { Route as AdminOrganizationRouteImport } from './routes/admin.organization'
import { Route as AdminOpeningHallRouteImport } from './routes/admin.opening-hall'
import { Route as AdminNotificationManageRouteImport } from './routes/admin.notification-manage'
import { Route as AdminNoticePublishRouteImport } from './routes/admin.notice-publish'
import { Route as AdminNoticeListRouteImport } from './routes/admin.notice-list'
import { Route as AdminMessageCenterRouteImport } from './routes/admin.message-center'
import { Route as AdminForbiddenRouteImport } from './routes/admin.forbidden'
import { Route as AdminFeeManageRouteImport } from './routes/admin.fee-manage'
import { Route as AdminExpertTasksRouteImport } from './routes/admin.expert-tasks'
import { Route as AdminExpertProjectRouteImport } from './routes/admin.expert-project'
import { Route as AdminExpertProfileRouteImport } from './routes/admin.expert-profile'
import { Route as AdminExpertExtractionRouteImport } from './routes/admin.expert-extraction'
import { Route as AdminEvaluationHallRouteImport } from './routes/admin.evaluation-hall'
import { Route as AdminDashboardRouteImport } from './routes/admin.dashboard'
import { Route as AdminBidderProjectsRouteImport } from './routes/admin.bidder-projects'
import { Route as AdminBidUploadRouteImport } from './routes/admin.bid-upload'
import { Route as AdminBidQuoteRouteImport } from './routes/admin.bid-quote'
import { Route as AdminBidDownloadRouteImport } from './routes/admin.bid-download'
import { Route as AdminAwardNoticeRouteImport } from './routes/admin.award-notice'
import { Route as AdminAwardConfirmRouteImport } from './routes/admin.award-confirm'
import { Route as AdminApprovalFlowConfigRouteImport } from './routes/admin.approval-flow-config'
import { Route as AdminApprovalCenterRouteImport } from './routes/admin.approval-center'
import { Route as AdminAnalyticsRouteImport } from './routes/admin.analytics'
import { Route as AdminAdminUsersRouteImport } from './routes/admin.admin-users'
import { Route as AdminAdminSupplierAuditRouteImport } from './routes/admin.admin-supplier-audit'
import { Route as AdminAdminNewsRouteImport } from './routes/admin.admin-news'
import { Route as AdminAdminLogsRouteImport } from './routes/admin.admin-logs'
import { Route as AdminAdminDictionaryRouteImport } from './routes/admin.admin-dictionary'
import { Route as AdminAdminDashboardRouteImport } from './routes/admin.admin-dashboard'
import { Route as AdminProjectsIndexRouteImport } from './routes/admin.projects.index'
import { Route as AdminProcurementRequirementsIndexRouteImport } from './routes/admin.procurement-requirements.index'
import { Route as AdminProjectsTrackRouteImport } from './routes/admin.projects.track'
import { Route as AdminProjectsCreateRouteImport } from './routes/admin.projects.create'
import { Route as AdminProcurementRequirementsEditRouteImport } from './routes/admin.procurement-requirements.edit'
import { Route as AdminProjectsDetailIdRouteImport } from './routes/admin.projects.detail.$id'

const ReviewChangeListRoute = ReviewChangeListRouteImport.update({
  id: '/review-change-list',
  path: '/review-change-list',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() =>
  import('./routes/review-change-list.lazy').then((d) => d.Route),
)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/register.lazy').then((d) => d.Route))
const NewsRoute = NewsRouteImport.update({
  id: '/news',
  path: '/news',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/news.lazy').then((d) => d.Route))
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/login.lazy').then((d) => d.Route))
const HelpRoute = HelpRouteImport.update({
  id: '/help',
  path: '/help',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/help.lazy').then((d) => d.Route))
const DownloadsRoute = DownloadsRouteImport.update({
  id: '/downloads',
  path: '/downloads',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/downloads.lazy').then((d) => d.Route))
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/contact.lazy').then((d) => d.Route))
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/index.lazy').then((d) => d.Route))
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRoute,
} as any).lazy(() => import('./routes/admin.index.lazy').then((d) => d.Route))
const NoticeIdRoute = NoticeIdRouteImport.update({
  id: '/notice/$id',
  path: '/notice/$id',
  getParentRoute: () => rootRouteImport,
} as any).lazy(() => import('./routes/notice.$id.lazy').then((d) => d.Route))
const AdminTodoCenterRoute = AdminTodoCenterRouteImport.update({
  id: '/todo-center',
  path: '/todo-center',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin.todo-center.lazy').then((d) => d.Route),
)
const AdminTenderDocRoute = AdminTenderDocRouteImport.update({
  id: '/tender-doc',
  path: '/tender-doc',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin.tender-doc.lazy').then((d) => d.Route),
)
const AdminTemplateManageRoute = AdminTemplateManageRouteImport.update({
  id: '/template-manage',
  path: '/template-manage',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin.template-manage.lazy').then((d) => d.Route),
)
const AdminSystemSettingsRoute = AdminSystemSettingsRouteImport.update({
  id: '/system-settings',
  path: '/system-settings',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin.system-settings.lazy').then((d) => d.Route),
)
const AdminSupplierProfileRoute = AdminSupplierProfileRouteImport.update({
  id: '/supplier-profile',
  path: '/supplier-profile',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin.supplier-profile.lazy').then((d) => d.Route),
)
const AdminSupplierAuthorizationRoute =
  AdminSupplierAuthorizationRouteImport.update({
    id: '/supplier-authorization',
    path: '/supplier-authorization',
    getParentRoute: () => AdminRoute,
  } as any).lazy(() =>
    import('./routes/admin.supplier-authorization.lazy').then((d) => d.Route),
  )
const AdminSupervisorLogsRoute = AdminSupervisorLogsRouteImport.update({
  id: '/supervisor-logs',
  path: '/supervisor-logs',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin.supervisor-logs.lazy').then((d) => d.Route),
)
const AdminSupervisorHallRoute = AdminSupervisorHallRouteImport.update({
  id: '/supervisor-hall',
  path: '/supervisor-hall',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin.supervisor-hall.lazy').then((d) => d.Route),
)
const AdminSupervisorAbnormalRoute = AdminSupervisorAbnormalRouteImport.update({
  id: '/supervisor-abnormal',
  path: '/supervisor-abnormal',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin.supervisor-abnormal.lazy').then((d) => d.Route),
)
const AdminSubAccountsRoute = AdminSubAccountsRouteImport.update({
  id: '/sub-accounts',
  path: '/sub-accounts',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin.sub-accounts.lazy').then((d) => d.Route),
)
const AdminReviewChangeListRoute = AdminReviewChangeListRouteImport.update({
  id: '/review-change-list',
  path: '/review-change-list',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin.review-change-list.lazy').then((d) => d.Route),
)
const AdminProjectsRoute = AdminProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AdminRoute,
} as any)
const AdminProcurementRequirementsRoute =
  AdminProcurementRequirementsRouteImport.update({
    id: '/procurement-requirements',
    path: '/procurement-requirements',
    getParentRoute: () => AdminRoute,
  } as any)
const AdminOrganizationRoute = AdminOrganizationRouteImport.update({
  id: '/organization',
  path: '/organization',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin.organization.lazy').then((d) => d.Route),
)
const AdminOpeningHallRoute = AdminOpeningHallRouteImport.update({
  id: '/opening-hall',
  path: '/opening-hall',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin.opening-hall.lazy').then((d) => d.Route),
)
const AdminNotificationManageRoute = AdminNotificationManageRouteImport.update({
  id: '/notification-manage',
  path: '/notification-manage',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin.notification-manage.lazy').then((d) => d.Route),
)
const AdminNoticePublishRoute = AdminNoticePublishRouteImport.update({
  id: '/notice-publish',
  path: '/notice-publish',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin.notice-publish.lazy').then((d) => d.Route),
)
const AdminNoticeListRoute = AdminNoticeListRouteImport.update({
  id: '/notice-list',
  path: '/notice-list',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin.notice-list.lazy').then((d) => d.Route),
)
const AdminMessageCenterRoute = AdminMessageCenterRouteImport.update({
  id: '/message-center',
  path: '/message-center',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin.message-center.lazy').then((d) => d.Route),
)
const AdminForbiddenRoute = AdminForbiddenRouteImport.update({
  id: '/forbidden',
  path: '/forbidden',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin.forbidden.lazy').then((d) => d.Route),
)
const AdminFeeManageRoute = AdminFeeManageRouteImport.update({
  id: '/fee-manage',
  path: '/fee-manage',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin.fee-manage.lazy').then((d) => d.Route),
)
const AdminExpertTasksRoute = AdminExpertTasksRouteImport.update({
  id: '/expert-tasks',
  path: '/expert-tasks',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin.expert-tasks.lazy').then((d) => d.Route),
)
const AdminExpertProjectRoute = AdminExpertProjectRouteImport.update({
  id: '/expert-project',
  path: '/expert-project',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin.expert-project.lazy').then((d) => d.Route),
)
const AdminExpertProfileRoute = AdminExpertProfileRouteImport.update({
  id: '/expert-profile',
  path: '/expert-profile',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin.expert-profile.lazy').then((d) => d.Route),
)
const AdminExpertExtractionRoute = AdminExpertExtractionRouteImport.update({
  id: '/expert-extraction',
  path: '/expert-extraction',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin.expert-extraction.lazy').then((d) => d.Route),
)
const AdminEvaluationHallRoute = AdminEvaluationHallRouteImport.update({
  id: '/evaluation-hall',
  path: '/evaluation-hall',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin.evaluation-hall.lazy').then((d) => d.Route),
)
const AdminDashboardRoute = AdminDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin.dashboard.lazy').then((d) => d.Route),
)
const AdminBidderProjectsRoute = AdminBidderProjectsRouteImport.update({
  id: '/bidder-projects',
  path: '/bidder-projects',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin.bidder-projects.lazy').then((d) => d.Route),
)
const AdminBidUploadRoute = AdminBidUploadRouteImport.update({
  id: '/bid-upload',
  path: '/bid-upload',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin.bid-upload.lazy').then((d) => d.Route),
)
const AdminBidQuoteRoute = AdminBidQuoteRouteImport.update({
  id: '/bid-quote',
  path: '/bid-quote',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin.bid-quote.lazy').then((d) => d.Route),
)
const AdminBidDownloadRoute = AdminBidDownloadRouteImport.update({
  id: '/bid-download',
  path: '/bid-download',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin.bid-download.lazy').then((d) => d.Route),
)
const AdminAwardNoticeRoute = AdminAwardNoticeRouteImport.update({
  id: '/award-notice',
  path: '/award-notice',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin.award-notice.lazy').then((d) => d.Route),
)
const AdminAwardConfirmRoute = AdminAwardConfirmRouteImport.update({
  id: '/award-confirm',
  path: '/award-confirm',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin.award-confirm.lazy').then((d) => d.Route),
)
const AdminApprovalFlowConfigRoute = AdminApprovalFlowConfigRouteImport.update({
  id: '/approval-flow-config',
  path: '/approval-flow-config',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin.approval-flow-config.lazy').then((d) => d.Route),
)
const AdminApprovalCenterRoute = AdminApprovalCenterRouteImport.update({
  id: '/approval-center',
  path: '/approval-center',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin.approval-center.lazy').then((d) => d.Route),
)
const AdminAnalyticsRoute = AdminAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin.analytics.lazy').then((d) => d.Route),
)
const AdminAdminUsersRoute = AdminAdminUsersRouteImport.update({
  id: '/admin-users',
  path: '/admin-users',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin.admin-users.lazy').then((d) => d.Route),
)
const AdminAdminSupplierAuditRoute = AdminAdminSupplierAuditRouteImport.update({
  id: '/admin-supplier-audit',
  path: '/admin-supplier-audit',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin.admin-supplier-audit.lazy').then((d) => d.Route),
)
const AdminAdminNewsRoute = AdminAdminNewsRouteImport.update({
  id: '/admin-news',
  path: '/admin-news',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin.admin-news.lazy').then((d) => d.Route),
)
const AdminAdminLogsRoute = AdminAdminLogsRouteImport.update({
  id: '/admin-logs',
  path: '/admin-logs',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin.admin-logs.lazy').then((d) => d.Route),
)
const AdminAdminDictionaryRoute = AdminAdminDictionaryRouteImport.update({
  id: '/admin-dictionary',
  path: '/admin-dictionary',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin.admin-dictionary.lazy').then((d) => d.Route),
)
const AdminAdminDashboardRoute = AdminAdminDashboardRouteImport.update({
  id: '/admin-dashboard',
  path: '/admin-dashboard',
  getParentRoute: () => AdminRoute,
} as any).lazy(() =>
  import('./routes/admin.admin-dashboard.lazy').then((d) => d.Route),
)
const AdminProjectsIndexRoute = AdminProjectsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminProjectsRoute,
} as any).lazy(() =>
  import('./routes/admin.projects.index.lazy').then((d) => d.Route),
)
const AdminProcurementRequirementsIndexRoute =
  AdminProcurementRequirementsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => AdminProcurementRequirementsRoute,
  } as any).lazy(() =>
    import('./routes/admin.procurement-requirements.index.lazy').then(
      (d) => d.Route,
    ),
  )
const AdminProjectsTrackRoute = AdminProjectsTrackRouteImport.update({
  id: '/track',
  path: '/track',
  getParentRoute: () => AdminProjectsRoute,
} as any).lazy(() =>
  import('./routes/admin.projects.track.lazy').then((d) => d.Route),
)
const AdminProjectsCreateRoute = AdminProjectsCreateRouteImport.update({
  id: '/create',
  path: '/create',
  getParentRoute: () => AdminProjectsRoute,
} as any).lazy(() =>
  import('./routes/admin.projects.create.lazy').then((d) => d.Route),
)
const AdminProcurementRequirementsEditRoute =
  AdminProcurementRequirementsEditRouteImport.update({
    id: '/edit',
    path: '/edit',
    getParentRoute: () => AdminProcurementRequirementsRoute,
  } as any).lazy(() =>
    import('./routes/admin.procurement-requirements.edit.lazy').then(
      (d) => d.Route,
    ),
  )
const AdminProjectsDetailIdRoute = AdminProjectsDetailIdRouteImport.update({
  id: '/detail/$id',
  path: '/detail/$id',
  getParentRoute: () => AdminProjectsRoute,
} as any).lazy(() =>
  import('./routes/admin.projects.detail.$id.lazy').then((d) => d.Route),
)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/downloads': typeof DownloadsRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRoute
  '/register': typeof RegisterRoute
  '/review-change-list': typeof ReviewChangeListRoute
  '/admin/admin-dashboard': typeof AdminAdminDashboardRoute
  '/admin/admin-dictionary': typeof AdminAdminDictionaryRoute
  '/admin/admin-logs': typeof AdminAdminLogsRoute
  '/admin/admin-news': typeof AdminAdminNewsRoute
  '/admin/admin-supplier-audit': typeof AdminAdminSupplierAuditRoute
  '/admin/admin-users': typeof AdminAdminUsersRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/approval-center': typeof AdminApprovalCenterRoute
  '/admin/approval-flow-config': typeof AdminApprovalFlowConfigRoute
  '/admin/award-confirm': typeof AdminAwardConfirmRoute
  '/admin/award-notice': typeof AdminAwardNoticeRoute
  '/admin/bid-download': typeof AdminBidDownloadRoute
  '/admin/bid-quote': typeof AdminBidQuoteRoute
  '/admin/bid-upload': typeof AdminBidUploadRoute
  '/admin/bidder-projects': typeof AdminBidderProjectsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/evaluation-hall': typeof AdminEvaluationHallRoute
  '/admin/expert-extraction': typeof AdminExpertExtractionRoute
  '/admin/expert-profile': typeof AdminExpertProfileRoute
  '/admin/expert-project': typeof AdminExpertProjectRoute
  '/admin/expert-tasks': typeof AdminExpertTasksRoute
  '/admin/fee-manage': typeof AdminFeeManageRoute
  '/admin/forbidden': typeof AdminForbiddenRoute
  '/admin/message-center': typeof AdminMessageCenterRoute
  '/admin/notice-list': typeof AdminNoticeListRoute
  '/admin/notice-publish': typeof AdminNoticePublishRoute
  '/admin/notification-manage': typeof AdminNotificationManageRoute
  '/admin/opening-hall': typeof AdminOpeningHallRoute
  '/admin/organization': typeof AdminOrganizationRoute
  '/admin/procurement-requirements': typeof AdminProcurementRequirementsRouteWithChildren
  '/admin/projects': typeof AdminProjectsRouteWithChildren
  '/admin/review-change-list': typeof AdminReviewChangeListRoute
  '/admin/sub-accounts': typeof AdminSubAccountsRoute
  '/admin/supervisor-abnormal': typeof AdminSupervisorAbnormalRoute
  '/admin/supervisor-hall': typeof AdminSupervisorHallRoute
  '/admin/supervisor-logs': typeof AdminSupervisorLogsRoute
  '/admin/supplier-authorization': typeof AdminSupplierAuthorizationRoute
  '/admin/supplier-profile': typeof AdminSupplierProfileRoute
  '/admin/system-settings': typeof AdminSystemSettingsRoute
  '/admin/template-manage': typeof AdminTemplateManageRoute
  '/admin/tender-doc': typeof AdminTenderDocRoute
  '/admin/todo-center': typeof AdminTodoCenterRoute
  '/notice/$id': typeof NoticeIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/procurement-requirements/edit': typeof AdminProcurementRequirementsEditRoute
  '/admin/projects/create': typeof AdminProjectsCreateRoute
  '/admin/projects/track': typeof AdminProjectsTrackRoute
  '/admin/procurement-requirements/': typeof AdminProcurementRequirementsIndexRoute
  '/admin/projects/': typeof AdminProjectsIndexRoute
  '/admin/projects/detail/$id': typeof AdminProjectsDetailIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contact': typeof ContactRoute
  '/downloads': typeof DownloadsRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRoute
  '/register': typeof RegisterRoute
  '/review-change-list': typeof ReviewChangeListRoute
  '/admin/admin-dashboard': typeof AdminAdminDashboardRoute
  '/admin/admin-dictionary': typeof AdminAdminDictionaryRoute
  '/admin/admin-logs': typeof AdminAdminLogsRoute
  '/admin/admin-news': typeof AdminAdminNewsRoute
  '/admin/admin-supplier-audit': typeof AdminAdminSupplierAuditRoute
  '/admin/admin-users': typeof AdminAdminUsersRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/approval-center': typeof AdminApprovalCenterRoute
  '/admin/approval-flow-config': typeof AdminApprovalFlowConfigRoute
  '/admin/award-confirm': typeof AdminAwardConfirmRoute
  '/admin/award-notice': typeof AdminAwardNoticeRoute
  '/admin/bid-download': typeof AdminBidDownloadRoute
  '/admin/bid-quote': typeof AdminBidQuoteRoute
  '/admin/bid-upload': typeof AdminBidUploadRoute
  '/admin/bidder-projects': typeof AdminBidderProjectsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/evaluation-hall': typeof AdminEvaluationHallRoute
  '/admin/expert-extraction': typeof AdminExpertExtractionRoute
  '/admin/expert-profile': typeof AdminExpertProfileRoute
  '/admin/expert-project': typeof AdminExpertProjectRoute
  '/admin/expert-tasks': typeof AdminExpertTasksRoute
  '/admin/fee-manage': typeof AdminFeeManageRoute
  '/admin/forbidden': typeof AdminForbiddenRoute
  '/admin/message-center': typeof AdminMessageCenterRoute
  '/admin/notice-list': typeof AdminNoticeListRoute
  '/admin/notice-publish': typeof AdminNoticePublishRoute
  '/admin/notification-manage': typeof AdminNotificationManageRoute
  '/admin/opening-hall': typeof AdminOpeningHallRoute
  '/admin/organization': typeof AdminOrganizationRoute
  '/admin/review-change-list': typeof AdminReviewChangeListRoute
  '/admin/sub-accounts': typeof AdminSubAccountsRoute
  '/admin/supervisor-abnormal': typeof AdminSupervisorAbnormalRoute
  '/admin/supervisor-hall': typeof AdminSupervisorHallRoute
  '/admin/supervisor-logs': typeof AdminSupervisorLogsRoute
  '/admin/supplier-authorization': typeof AdminSupplierAuthorizationRoute
  '/admin/supplier-profile': typeof AdminSupplierProfileRoute
  '/admin/system-settings': typeof AdminSystemSettingsRoute
  '/admin/template-manage': typeof AdminTemplateManageRoute
  '/admin/tender-doc': typeof AdminTenderDocRoute
  '/admin/todo-center': typeof AdminTodoCenterRoute
  '/notice/$id': typeof NoticeIdRoute
  '/admin': typeof AdminIndexRoute
  '/admin/procurement-requirements/edit': typeof AdminProcurementRequirementsEditRoute
  '/admin/projects/create': typeof AdminProjectsCreateRoute
  '/admin/projects/track': typeof AdminProjectsTrackRoute
  '/admin/procurement-requirements': typeof AdminProcurementRequirementsIndexRoute
  '/admin/projects': typeof AdminProjectsIndexRoute
  '/admin/projects/detail/$id': typeof AdminProjectsDetailIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteWithChildren
  '/contact': typeof ContactRoute
  '/downloads': typeof DownloadsRoute
  '/help': typeof HelpRoute
  '/login': typeof LoginRoute
  '/news': typeof NewsRoute
  '/register': typeof RegisterRoute
  '/review-change-list': typeof ReviewChangeListRoute
  '/admin/admin-dashboard': typeof AdminAdminDashboardRoute
  '/admin/admin-dictionary': typeof AdminAdminDictionaryRoute
  '/admin/admin-logs': typeof AdminAdminLogsRoute
  '/admin/admin-news': typeof AdminAdminNewsRoute
  '/admin/admin-supplier-audit': typeof AdminAdminSupplierAuditRoute
  '/admin/admin-users': typeof AdminAdminUsersRoute
  '/admin/analytics': typeof AdminAnalyticsRoute
  '/admin/approval-center': typeof AdminApprovalCenterRoute
  '/admin/approval-flow-config': typeof AdminApprovalFlowConfigRoute
  '/admin/award-confirm': typeof AdminAwardConfirmRoute
  '/admin/award-notice': typeof AdminAwardNoticeRoute
  '/admin/bid-download': typeof AdminBidDownloadRoute
  '/admin/bid-quote': typeof AdminBidQuoteRoute
  '/admin/bid-upload': typeof AdminBidUploadRoute
  '/admin/bidder-projects': typeof AdminBidderProjectsRoute
  '/admin/dashboard': typeof AdminDashboardRoute
  '/admin/evaluation-hall': typeof AdminEvaluationHallRoute
  '/admin/expert-extraction': typeof AdminExpertExtractionRoute
  '/admin/expert-profile': typeof AdminExpertProfileRoute
  '/admin/expert-project': typeof AdminExpertProjectRoute
  '/admin/expert-tasks': typeof AdminExpertTasksRoute
  '/admin/fee-manage': typeof AdminFeeManageRoute
  '/admin/forbidden': typeof AdminForbiddenRoute
  '/admin/message-center': typeof AdminMessageCenterRoute
  '/admin/notice-list': typeof AdminNoticeListRoute
  '/admin/notice-publish': typeof AdminNoticePublishRoute
  '/admin/notification-manage': typeof AdminNotificationManageRoute
  '/admin/opening-hall': typeof AdminOpeningHallRoute
  '/admin/organization': typeof AdminOrganizationRoute
  '/admin/procurement-requirements': typeof AdminProcurementRequirementsRouteWithChildren
  '/admin/projects': typeof AdminProjectsRouteWithChildren
  '/admin/review-change-list': typeof AdminReviewChangeListRoute
  '/admin/sub-accounts': typeof AdminSubAccountsRoute
  '/admin/supervisor-abnormal': typeof AdminSupervisorAbnormalRoute
  '/admin/supervisor-hall': typeof AdminSupervisorHallRoute
  '/admin/supervisor-logs': typeof AdminSupervisorLogsRoute
  '/admin/supplier-authorization': typeof AdminSupplierAuthorizationRoute
  '/admin/supplier-profile': typeof AdminSupplierProfileRoute
  '/admin/system-settings': typeof AdminSystemSettingsRoute
  '/admin/template-manage': typeof AdminTemplateManageRoute
  '/admin/tender-doc': typeof AdminTenderDocRoute
  '/admin/todo-center': typeof AdminTodoCenterRoute
  '/notice/$id': typeof NoticeIdRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/procurement-requirements/edit': typeof AdminProcurementRequirementsEditRoute
  '/admin/projects/create': typeof AdminProjectsCreateRoute
  '/admin/projects/track': typeof AdminProjectsTrackRoute
  '/admin/procurement-requirements/': typeof AdminProcurementRequirementsIndexRoute
  '/admin/projects/': typeof AdminProjectsIndexRoute
  '/admin/projects/detail/$id': typeof AdminProjectsDetailIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/contact'
    | '/downloads'
    | '/help'
    | '/login'
    | '/news'
    | '/register'
    | '/review-change-list'
    | '/admin/admin-dashboard'
    | '/admin/admin-dictionary'
    | '/admin/admin-logs'
    | '/admin/admin-news'
    | '/admin/admin-supplier-audit'
    | '/admin/admin-users'
    | '/admin/analytics'
    | '/admin/approval-center'
    | '/admin/approval-flow-config'
    | '/admin/award-confirm'
    | '/admin/award-notice'
    | '/admin/bid-download'
    | '/admin/bid-quote'
    | '/admin/bid-upload'
    | '/admin/bidder-projects'
    | '/admin/dashboard'
    | '/admin/evaluation-hall'
    | '/admin/expert-extraction'
    | '/admin/expert-profile'
    | '/admin/expert-project'
    | '/admin/expert-tasks'
    | '/admin/fee-manage'
    | '/admin/forbidden'
    | '/admin/message-center'
    | '/admin/notice-list'
    | '/admin/notice-publish'
    | '/admin/notification-manage'
    | '/admin/opening-hall'
    | '/admin/organization'
    | '/admin/procurement-requirements'
    | '/admin/projects'
    | '/admin/review-change-list'
    | '/admin/sub-accounts'
    | '/admin/supervisor-abnormal'
    | '/admin/supervisor-hall'
    | '/admin/supervisor-logs'
    | '/admin/supplier-authorization'
    | '/admin/supplier-profile'
    | '/admin/system-settings'
    | '/admin/template-manage'
    | '/admin/tender-doc'
    | '/admin/todo-center'
    | '/notice/$id'
    | '/admin/'
    | '/admin/procurement-requirements/edit'
    | '/admin/projects/create'
    | '/admin/projects/track'
    | '/admin/procurement-requirements/'
    | '/admin/projects/'
    | '/admin/projects/detail/$id'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contact'
    | '/downloads'
    | '/help'
    | '/login'
    | '/news'
    | '/register'
    | '/review-change-list'
    | '/admin/admin-dashboard'
    | '/admin/admin-dictionary'
    | '/admin/admin-logs'
    | '/admin/admin-news'
    | '/admin/admin-supplier-audit'
    | '/admin/admin-users'
    | '/admin/analytics'
    | '/admin/approval-center'
    | '/admin/approval-flow-config'
    | '/admin/award-confirm'
    | '/admin/award-notice'
    | '/admin/bid-download'
    | '/admin/bid-quote'
    | '/admin/bid-upload'
    | '/admin/bidder-projects'
    | '/admin/dashboard'
    | '/admin/evaluation-hall'
    | '/admin/expert-extraction'
    | '/admin/expert-profile'
    | '/admin/expert-project'
    | '/admin/expert-tasks'
    | '/admin/fee-manage'
    | '/admin/forbidden'
    | '/admin/message-center'
    | '/admin/notice-list'
    | '/admin/notice-publish'
    | '/admin/notification-manage'
    | '/admin/opening-hall'
    | '/admin/organization'
    | '/admin/review-change-list'
    | '/admin/sub-accounts'
    | '/admin/supervisor-abnormal'
    | '/admin/supervisor-hall'
    | '/admin/supervisor-logs'
    | '/admin/supplier-authorization'
    | '/admin/supplier-profile'
    | '/admin/system-settings'
    | '/admin/template-manage'
    | '/admin/tender-doc'
    | '/admin/todo-center'
    | '/notice/$id'
    | '/admin'
    | '/admin/procurement-requirements/edit'
    | '/admin/projects/create'
    | '/admin/projects/track'
    | '/admin/procurement-requirements'
    | '/admin/projects'
    | '/admin/projects/detail/$id'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/contact'
    | '/downloads'
    | '/help'
    | '/login'
    | '/news'
    | '/register'
    | '/review-change-list'
    | '/admin/admin-dashboard'
    | '/admin/admin-dictionary'
    | '/admin/admin-logs'
    | '/admin/admin-news'
    | '/admin/admin-supplier-audit'
    | '/admin/admin-users'
    | '/admin/analytics'
    | '/admin/approval-center'
    | '/admin/approval-flow-config'
    | '/admin/award-confirm'
    | '/admin/award-notice'
    | '/admin/bid-download'
    | '/admin/bid-quote'
    | '/admin/bid-upload'
    | '/admin/bidder-projects'
    | '/admin/dashboard'
    | '/admin/evaluation-hall'
    | '/admin/expert-extraction'
    | '/admin/expert-profile'
    | '/admin/expert-project'
    | '/admin/expert-tasks'
    | '/admin/fee-manage'
    | '/admin/forbidden'
    | '/admin/message-center'
    | '/admin/notice-list'
    | '/admin/notice-publish'
    | '/admin/notification-manage'
    | '/admin/opening-hall'
    | '/admin/organization'
    | '/admin/procurement-requirements'
    | '/admin/projects'
    | '/admin/review-change-list'
    | '/admin/sub-accounts'
    | '/admin/supervisor-abnormal'
    | '/admin/supervisor-hall'
    | '/admin/supervisor-logs'
    | '/admin/supplier-authorization'
    | '/admin/supplier-profile'
    | '/admin/system-settings'
    | '/admin/template-manage'
    | '/admin/tender-doc'
    | '/admin/todo-center'
    | '/notice/$id'
    | '/admin/'
    | '/admin/procurement-requirements/edit'
    | '/admin/projects/create'
    | '/admin/projects/track'
    | '/admin/procurement-requirements/'
    | '/admin/projects/'
    | '/admin/projects/detail/$id'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRoute: typeof AdminRouteWithChildren
  ContactRoute: typeof ContactRoute
  DownloadsRoute: typeof DownloadsRoute
  HelpRoute: typeof HelpRoute
  LoginRoute: typeof LoginRoute
  NewsRoute: typeof NewsRoute
  RegisterRoute: typeof RegisterRoute
  ReviewChangeListRoute: typeof ReviewChangeListRoute
  NoticeIdRoute: typeof NoticeIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/review-change-list': {
      id: '/review-change-list'
      path: '/review-change-list'
      fullPath: '/review-change-list'
      preLoaderRoute: typeof ReviewChangeListRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/news': {
      id: '/news'
      path: '/news'
      fullPath: '/news'
      preLoaderRoute: typeof NewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/help': {
      id: '/help'
      path: '/help'
      fullPath: '/help'
      preLoaderRoute: typeof HelpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/downloads': {
      id: '/downloads'
      path: '/downloads'
      fullPath: '/downloads'
      preLoaderRoute: typeof DownloadsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRoute
    }
    '/notice/$id': {
      id: '/notice/$id'
      path: '/notice/$id'
      fullPath: '/notice/$id'
      preLoaderRoute: typeof NoticeIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/todo-center': {
      id: '/admin/todo-center'
      path: '/todo-center'
      fullPath: '/admin/todo-center'
      preLoaderRoute: typeof AdminTodoCenterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/tender-doc': {
      id: '/admin/tender-doc'
      path: '/tender-doc'
      fullPath: '/admin/tender-doc'
      preLoaderRoute: typeof AdminTenderDocRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/template-manage': {
      id: '/admin/template-manage'
      path: '/template-manage'
      fullPath: '/admin/template-manage'
      preLoaderRoute: typeof AdminTemplateManageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/system-settings': {
      id: '/admin/system-settings'
      path: '/system-settings'
      fullPath: '/admin/system-settings'
      preLoaderRoute: typeof AdminSystemSettingsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/supplier-profile': {
      id: '/admin/supplier-profile'
      path: '/supplier-profile'
      fullPath: '/admin/supplier-profile'
      preLoaderRoute: typeof AdminSupplierProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/supplier-authorization': {
      id: '/admin/supplier-authorization'
      path: '/supplier-authorization'
      fullPath: '/admin/supplier-authorization'
      preLoaderRoute: typeof AdminSupplierAuthorizationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/supervisor-logs': {
      id: '/admin/supervisor-logs'
      path: '/supervisor-logs'
      fullPath: '/admin/supervisor-logs'
      preLoaderRoute: typeof AdminSupervisorLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/supervisor-hall': {
      id: '/admin/supervisor-hall'
      path: '/supervisor-hall'
      fullPath: '/admin/supervisor-hall'
      preLoaderRoute: typeof AdminSupervisorHallRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/supervisor-abnormal': {
      id: '/admin/supervisor-abnormal'
      path: '/supervisor-abnormal'
      fullPath: '/admin/supervisor-abnormal'
      preLoaderRoute: typeof AdminSupervisorAbnormalRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/sub-accounts': {
      id: '/admin/sub-accounts'
      path: '/sub-accounts'
      fullPath: '/admin/sub-accounts'
      preLoaderRoute: typeof AdminSubAccountsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/review-change-list': {
      id: '/admin/review-change-list'
      path: '/review-change-list'
      fullPath: '/admin/review-change-list'
      preLoaderRoute: typeof AdminReviewChangeListRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects': {
      id: '/admin/projects'
      path: '/projects'
      fullPath: '/admin/projects'
      preLoaderRoute: typeof AdminProjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/procurement-requirements': {
      id: '/admin/procurement-requirements'
      path: '/procurement-requirements'
      fullPath: '/admin/procurement-requirements'
      preLoaderRoute: typeof AdminProcurementRequirementsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/organization': {
      id: '/admin/organization'
      path: '/organization'
      fullPath: '/admin/organization'
      preLoaderRoute: typeof AdminOrganizationRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/opening-hall': {
      id: '/admin/opening-hall'
      path: '/opening-hall'
      fullPath: '/admin/opening-hall'
      preLoaderRoute: typeof AdminOpeningHallRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notification-manage': {
      id: '/admin/notification-manage'
      path: '/notification-manage'
      fullPath: '/admin/notification-manage'
      preLoaderRoute: typeof AdminNotificationManageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notice-publish': {
      id: '/admin/notice-publish'
      path: '/notice-publish'
      fullPath: '/admin/notice-publish'
      preLoaderRoute: typeof AdminNoticePublishRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/notice-list': {
      id: '/admin/notice-list'
      path: '/notice-list'
      fullPath: '/admin/notice-list'
      preLoaderRoute: typeof AdminNoticeListRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/message-center': {
      id: '/admin/message-center'
      path: '/message-center'
      fullPath: '/admin/message-center'
      preLoaderRoute: typeof AdminMessageCenterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/forbidden': {
      id: '/admin/forbidden'
      path: '/forbidden'
      fullPath: '/admin/forbidden'
      preLoaderRoute: typeof AdminForbiddenRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/fee-manage': {
      id: '/admin/fee-manage'
      path: '/fee-manage'
      fullPath: '/admin/fee-manage'
      preLoaderRoute: typeof AdminFeeManageRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/expert-tasks': {
      id: '/admin/expert-tasks'
      path: '/expert-tasks'
      fullPath: '/admin/expert-tasks'
      preLoaderRoute: typeof AdminExpertTasksRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/expert-project': {
      id: '/admin/expert-project'
      path: '/expert-project'
      fullPath: '/admin/expert-project'
      preLoaderRoute: typeof AdminExpertProjectRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/expert-profile': {
      id: '/admin/expert-profile'
      path: '/expert-profile'
      fullPath: '/admin/expert-profile'
      preLoaderRoute: typeof AdminExpertProfileRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/expert-extraction': {
      id: '/admin/expert-extraction'
      path: '/expert-extraction'
      fullPath: '/admin/expert-extraction'
      preLoaderRoute: typeof AdminExpertExtractionRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/evaluation-hall': {
      id: '/admin/evaluation-hall'
      path: '/evaluation-hall'
      fullPath: '/admin/evaluation-hall'
      preLoaderRoute: typeof AdminEvaluationHallRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/dashboard': {
      id: '/admin/dashboard'
      path: '/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bidder-projects': {
      id: '/admin/bidder-projects'
      path: '/bidder-projects'
      fullPath: '/admin/bidder-projects'
      preLoaderRoute: typeof AdminBidderProjectsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bid-upload': {
      id: '/admin/bid-upload'
      path: '/bid-upload'
      fullPath: '/admin/bid-upload'
      preLoaderRoute: typeof AdminBidUploadRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bid-quote': {
      id: '/admin/bid-quote'
      path: '/bid-quote'
      fullPath: '/admin/bid-quote'
      preLoaderRoute: typeof AdminBidQuoteRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/bid-download': {
      id: '/admin/bid-download'
      path: '/bid-download'
      fullPath: '/admin/bid-download'
      preLoaderRoute: typeof AdminBidDownloadRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/award-notice': {
      id: '/admin/award-notice'
      path: '/award-notice'
      fullPath: '/admin/award-notice'
      preLoaderRoute: typeof AdminAwardNoticeRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/award-confirm': {
      id: '/admin/award-confirm'
      path: '/award-confirm'
      fullPath: '/admin/award-confirm'
      preLoaderRoute: typeof AdminAwardConfirmRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/approval-flow-config': {
      id: '/admin/approval-flow-config'
      path: '/approval-flow-config'
      fullPath: '/admin/approval-flow-config'
      preLoaderRoute: typeof AdminApprovalFlowConfigRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/approval-center': {
      id: '/admin/approval-center'
      path: '/approval-center'
      fullPath: '/admin/approval-center'
      preLoaderRoute: typeof AdminApprovalCenterRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/analytics': {
      id: '/admin/analytics'
      path: '/analytics'
      fullPath: '/admin/analytics'
      preLoaderRoute: typeof AdminAnalyticsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/admin-users': {
      id: '/admin/admin-users'
      path: '/admin-users'
      fullPath: '/admin/admin-users'
      preLoaderRoute: typeof AdminAdminUsersRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/admin-supplier-audit': {
      id: '/admin/admin-supplier-audit'
      path: '/admin-supplier-audit'
      fullPath: '/admin/admin-supplier-audit'
      preLoaderRoute: typeof AdminAdminSupplierAuditRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/admin-news': {
      id: '/admin/admin-news'
      path: '/admin-news'
      fullPath: '/admin/admin-news'
      preLoaderRoute: typeof AdminAdminNewsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/admin-logs': {
      id: '/admin/admin-logs'
      path: '/admin-logs'
      fullPath: '/admin/admin-logs'
      preLoaderRoute: typeof AdminAdminLogsRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/admin-dictionary': {
      id: '/admin/admin-dictionary'
      path: '/admin-dictionary'
      fullPath: '/admin/admin-dictionary'
      preLoaderRoute: typeof AdminAdminDictionaryRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/admin-dashboard': {
      id: '/admin/admin-dashboard'
      path: '/admin-dashboard'
      fullPath: '/admin/admin-dashboard'
      preLoaderRoute: typeof AdminAdminDashboardRouteImport
      parentRoute: typeof AdminRoute
    }
    '/admin/projects/': {
      id: '/admin/projects/'
      path: '/'
      fullPath: '/admin/projects/'
      preLoaderRoute: typeof AdminProjectsIndexRouteImport
      parentRoute: typeof AdminProjectsRoute
    }
    '/admin/procurement-requirements/': {
      id: '/admin/procurement-requirements/'
      path: '/'
      fullPath: '/admin/procurement-requirements/'
      preLoaderRoute: typeof AdminProcurementRequirementsIndexRouteImport
      parentRoute: typeof AdminProcurementRequirementsRoute
    }
    '/admin/projects/track': {
      id: '/admin/projects/track'
      path: '/track'
      fullPath: '/admin/projects/track'
      preLoaderRoute: typeof AdminProjectsTrackRouteImport
      parentRoute: typeof AdminProjectsRoute
    }
    '/admin/projects/create': {
      id: '/admin/projects/create'
      path: '/create'
      fullPath: '/admin/projects/create'
      preLoaderRoute: typeof AdminProjectsCreateRouteImport
      parentRoute: typeof AdminProjectsRoute
    }
    '/admin/procurement-requirements/edit': {
      id: '/admin/procurement-requirements/edit'
      path: '/edit'
      fullPath: '/admin/procurement-requirements/edit'
      preLoaderRoute: typeof AdminProcurementRequirementsEditRouteImport
      parentRoute: typeof AdminProcurementRequirementsRoute
    }
    '/admin/projects/detail/$id': {
      id: '/admin/projects/detail/$id'
      path: '/detail/$id'
      fullPath: '/admin/projects/detail/$id'
      preLoaderRoute: typeof AdminProjectsDetailIdRouteImport
      parentRoute: typeof AdminProjectsRoute
    }
  }
}

interface AdminProcurementRequirementsRouteChildren {
  AdminProcurementRequirementsEditRoute: typeof AdminProcurementRequirementsEditRoute
  AdminProcurementRequirementsIndexRoute: typeof AdminProcurementRequirementsIndexRoute
}

const AdminProcurementRequirementsRouteChildren: AdminProcurementRequirementsRouteChildren =
  {
    AdminProcurementRequirementsEditRoute:
      AdminProcurementRequirementsEditRoute,
    AdminProcurementRequirementsIndexRoute:
      AdminProcurementRequirementsIndexRoute,
  }

const AdminProcurementRequirementsRouteWithChildren =
  AdminProcurementRequirementsRoute._addFileChildren(
    AdminProcurementRequirementsRouteChildren,
  )

interface AdminProjectsRouteChildren {
  AdminProjectsCreateRoute: typeof AdminProjectsCreateRoute
  AdminProjectsTrackRoute: typeof AdminProjectsTrackRoute
  AdminProjectsIndexRoute: typeof AdminProjectsIndexRoute
  AdminProjectsDetailIdRoute: typeof AdminProjectsDetailIdRoute
}

const AdminProjectsRouteChildren: AdminProjectsRouteChildren = {
  AdminProjectsCreateRoute: AdminProjectsCreateRoute,
  AdminProjectsTrackRoute: AdminProjectsTrackRoute,
  AdminProjectsIndexRoute: AdminProjectsIndexRoute,
  AdminProjectsDetailIdRoute: AdminProjectsDetailIdRoute,
}

const AdminProjectsRouteWithChildren = AdminProjectsRoute._addFileChildren(
  AdminProjectsRouteChildren,
)

interface AdminRouteChildren {
  AdminAdminDashboardRoute: typeof AdminAdminDashboardRoute
  AdminAdminDictionaryRoute: typeof AdminAdminDictionaryRoute
  AdminAdminLogsRoute: typeof AdminAdminLogsRoute
  AdminAdminNewsRoute: typeof AdminAdminNewsRoute
  AdminAdminSupplierAuditRoute: typeof AdminAdminSupplierAuditRoute
  AdminAdminUsersRoute: typeof AdminAdminUsersRoute
  AdminAnalyticsRoute: typeof AdminAnalyticsRoute
  AdminApprovalCenterRoute: typeof AdminApprovalCenterRoute
  AdminApprovalFlowConfigRoute: typeof AdminApprovalFlowConfigRoute
  AdminAwardConfirmRoute: typeof AdminAwardConfirmRoute
  AdminAwardNoticeRoute: typeof AdminAwardNoticeRoute
  AdminBidDownloadRoute: typeof AdminBidDownloadRoute
  AdminBidQuoteRoute: typeof AdminBidQuoteRoute
  AdminBidUploadRoute: typeof AdminBidUploadRoute
  AdminBidderProjectsRoute: typeof AdminBidderProjectsRoute
  AdminDashboardRoute: typeof AdminDashboardRoute
  AdminEvaluationHallRoute: typeof AdminEvaluationHallRoute
  AdminExpertExtractionRoute: typeof AdminExpertExtractionRoute
  AdminExpertProfileRoute: typeof AdminExpertProfileRoute
  AdminExpertProjectRoute: typeof AdminExpertProjectRoute
  AdminExpertTasksRoute: typeof AdminExpertTasksRoute
  AdminFeeManageRoute: typeof AdminFeeManageRoute
  AdminForbiddenRoute: typeof AdminForbiddenRoute
  AdminMessageCenterRoute: typeof AdminMessageCenterRoute
  AdminNoticeListRoute: typeof AdminNoticeListRoute
  AdminNoticePublishRoute: typeof AdminNoticePublishRoute
  AdminNotificationManageRoute: typeof AdminNotificationManageRoute
  AdminOpeningHallRoute: typeof AdminOpeningHallRoute
  AdminOrganizationRoute: typeof AdminOrganizationRoute
  AdminProcurementRequirementsRoute: typeof AdminProcurementRequirementsRouteWithChildren
  AdminProjectsRoute: typeof AdminProjectsRouteWithChildren
  AdminReviewChangeListRoute: typeof AdminReviewChangeListRoute
  AdminSubAccountsRoute: typeof AdminSubAccountsRoute
  AdminSupervisorAbnormalRoute: typeof AdminSupervisorAbnormalRoute
  AdminSupervisorHallRoute: typeof AdminSupervisorHallRoute
  AdminSupervisorLogsRoute: typeof AdminSupervisorLogsRoute
  AdminSupplierAuthorizationRoute: typeof AdminSupplierAuthorizationRoute
  AdminSupplierProfileRoute: typeof AdminSupplierProfileRoute
  AdminSystemSettingsRoute: typeof AdminSystemSettingsRoute
  AdminTemplateManageRoute: typeof AdminTemplateManageRoute
  AdminTenderDocRoute: typeof AdminTenderDocRoute
  AdminTodoCenterRoute: typeof AdminTodoCenterRoute
  AdminIndexRoute: typeof AdminIndexRoute
}

const AdminRouteChildren: AdminRouteChildren = {
  AdminAdminDashboardRoute: AdminAdminDashboardRoute,
  AdminAdminDictionaryRoute: AdminAdminDictionaryRoute,
  AdminAdminLogsRoute: AdminAdminLogsRoute,
  AdminAdminNewsRoute: AdminAdminNewsRoute,
  AdminAdminSupplierAuditRoute: AdminAdminSupplierAuditRoute,
  AdminAdminUsersRoute: AdminAdminUsersRoute,
  AdminAnalyticsRoute: AdminAnalyticsRoute,
  AdminApprovalCenterRoute: AdminApprovalCenterRoute,
  AdminApprovalFlowConfigRoute: AdminApprovalFlowConfigRoute,
  AdminAwardConfirmRoute: AdminAwardConfirmRoute,
  AdminAwardNoticeRoute: AdminAwardNoticeRoute,
  AdminBidDownloadRoute: AdminBidDownloadRoute,
  AdminBidQuoteRoute: AdminBidQuoteRoute,
  AdminBidUploadRoute: AdminBidUploadRoute,
  AdminBidderProjectsRoute: AdminBidderProjectsRoute,
  AdminDashboardRoute: AdminDashboardRoute,
  AdminEvaluationHallRoute: AdminEvaluationHallRoute,
  AdminExpertExtractionRoute: AdminExpertExtractionRoute,
  AdminExpertProfileRoute: AdminExpertProfileRoute,
  AdminExpertProjectRoute: AdminExpertProjectRoute,
  AdminExpertTasksRoute: AdminExpertTasksRoute,
  AdminFeeManageRoute: AdminFeeManageRoute,
  AdminForbiddenRoute: AdminForbiddenRoute,
  AdminMessageCenterRoute: AdminMessageCenterRoute,
  AdminNoticeListRoute: AdminNoticeListRoute,
  AdminNoticePublishRoute: AdminNoticePublishRoute,
  AdminNotificationManageRoute: AdminNotificationManageRoute,
  AdminOpeningHallRoute: AdminOpeningHallRoute,
  AdminOrganizationRoute: AdminOrganizationRoute,
  AdminProcurementRequirementsRoute:
    AdminProcurementRequirementsRouteWithChildren,
  AdminProjectsRoute: AdminProjectsRouteWithChildren,
  AdminReviewChangeListRoute: AdminReviewChangeListRoute,
  AdminSubAccountsRoute: AdminSubAccountsRoute,
  AdminSupervisorAbnormalRoute: AdminSupervisorAbnormalRoute,
  AdminSupervisorHallRoute: AdminSupervisorHallRoute,
  AdminSupervisorLogsRoute: AdminSupervisorLogsRoute,
  AdminSupplierAuthorizationRoute: AdminSupplierAuthorizationRoute,
  AdminSupplierProfileRoute: AdminSupplierProfileRoute,
  AdminSystemSettingsRoute: AdminSystemSettingsRoute,
  AdminTemplateManageRoute: AdminTemplateManageRoute,
  AdminTenderDocRoute: AdminTenderDocRoute,
  AdminTodoCenterRoute: AdminTodoCenterRoute,
  AdminIndexRoute: AdminIndexRoute,
}

const AdminRouteWithChildren = AdminRoute._addFileChildren(AdminRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRoute: AdminRouteWithChildren,
  ContactRoute: ContactRoute,
  DownloadsRoute: DownloadsRoute,
  HelpRoute: HelpRoute,
  LoginRoute: LoginRoute,
  NewsRoute: NewsRoute,
  RegisterRoute: RegisterRoute,
  ReviewChangeListRoute: ReviewChangeListRoute,
  NoticeIdRoute: NoticeIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
